"""
Email sender functionality for Case-Verify AI
"""
import smtplib
import ssl
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.base import MIMEBase
from email import encoders
import os
from typing import List, Optional
import streamlit as st

class EmailSender:
    """Email functionality for sending reports and notifications"""
    
    def __init__(self):
        self.smtp_server = os.getenv('SMTP_SERVER', 'smtp.gmail.com')
        self.smtp_port = int(os.getenv('SMTP_PORT', '587'))
        self.sender_email = os.getenv('SENDER_EMAIL', '')
        self.sender_password = os.getenv('SENDER_PASSWORD', '')
    
    def send_report_email(self, recipient_email: str, subject: str, body: str, 
                         attachments: List[dict] = None) -> bool:
        """Send email with report attachments"""
        try:
            # Create message
            msg = MIMEMultipart()
            msg['From'] = self.sender_email
            msg['To'] = recipient_email
            msg['Subject'] = subject
            
            # Add body to email
            msg.attach(MIMEText(body, 'html'))
            
            # Add attachments
            if attachments:
                for attachment in attachments:
                    self._add_attachment(msg, attachment)
            
            # Create SMTP session
            context = ssl.create_default_context()
            
            with smtplib.SMTP(self.smtp_server, self.smtp_port) as server:
                server.starttls(context=context)
                server.login(self.sender_email, self.sender_password)
                
                text = msg.as_string()
                server.sendmail(self.sender_email, recipient_email, text)
            
            return True
            
        except Exception as e:
            st.error(f"Email sending failed: {str(e)}")
            return False
    
    def _add_attachment(self, msg: MIMEMultipart, attachment: dict):
        """Add attachment to email message"""
        try:
            # attachment should be a dict with 'data', 'filename', and 'mime_type'
            part = MIMEBase('application', 'octet-stream')
            
            if isinstance(attachment['data'], bytes):
                part.set_payload(attachment['data'])
            else:
                part.set_payload(attachment['data'].getvalue())
            
            encoders.encode_base64(part)
            
            part.add_header(
                'Content-Disposition',
                f'attachment; filename= {attachment["filename"]}'
            )
            
            msg.attach(part)
            
        except Exception as e:
            st.warning(f"Failed to attach {attachment.get('filename', 'file')}: {str(e)}")
    
    def create_report_email_body(self, user_name: str, report_type: str, case_count: int) -> str:
        """Create HTML email body for report"""
        return f"""
        <html>
            <body style="font-family: Arial, sans-serif; line-height: 1.6; color: #333;">
                <div style="max-width: 600px; margin: 0 auto; padding: 20px;">
                    <div style="text-align: center; margin-bottom: 30px;">
                        <h1 style="color: #1e2951; margin-bottom: 10px;">Case-Verify AI</h1>
                        <h2 style="color: #722f37; margin-top: 0;">Legal Case Analysis Report</h2>
                    </div>
                    
                    <div style="background-color: #f8f9fa; padding: 20px; border-radius: 5px; margin-bottom: 20px;">
                        <p>Dear {user_name},</p>
                        
                        <p>Your {report_type} report has been generated successfully and is attached to this email.</p>
                        
                        <p><strong>Report Details:</strong></p>
                        <ul>
                            <li>Report Type: {report_type}</li>
                            <li>Number of Cases: {case_count}</li>
                            <li>Generated: {self._get_current_datetime()}</li>
                        </ul>
                    </div>
                    
                    <div style="background-color: #fff3cd; border-left: 4px solid #ffc107; padding: 15px; margin-bottom: 20px;">
                        <h4 style="color: #856404; margin-top: 0;">Important Disclaimer</h4>
                        <p style="margin-bottom: 0; color: #856404;">
                            This report is generated by Case-Verify AI for informational purposes only. 
                            It should not be considered as professional legal advice. Always consult with 
                            qualified legal practitioners for legal decisions.
                        </p>
                    </div>
                    
                    <div style="text-align: center; margin-top: 30px; padding-top: 20px; border-top: 1px solid #dee2e6;">
                        <p style="color: #6c757d; font-size: 14px;">
                            Generated by Case-Verify AI<br>
                            <a href="mailto:support@caseverify.ai" style="color: #1e2951;">support@caseverify.ai</a>
                        </p>
                    </div>
                </div>
            </body>
        </html>
        """
    
    def _get_current_datetime(self) -> str:
        """Get current datetime as formatted string"""
        from datetime import datetime
        return datetime.now().strftime('%Y-%m-%d %H:%M:%S')
    
    def is_configured(self) -> bool:
        """Check if email is properly configured"""
        return bool(self.sender_email and self.sender_password)
    
    def send_test_email(self, recipient_email: str) -> bool:
        """Send test email to verify configuration"""
        subject = "Case-Verify AI - Test Email"
        body = self.create_test_email_body()
        
        return self.send_report_email(recipient_email, subject, body)
    
    def create_test_email_body(self) -> str:
        """Create test email body"""
        return """
        <html>
            <body style="font-family: Arial, sans-serif; line-height: 1.6; color: #333;">
                <div style="max-width: 600px; margin: 0 auto; padding: 20px;">
                    <div style="text-align: center; margin-bottom: 30px;">
                        <h1 style="color: #1e2951;">Case-Verify AI</h1>
                        <h2 style="color: #722f37;">Email Configuration Test</h2>
                    </div>
                    
                    <div style="background-color: #d4edda; border-left: 4px solid #28a745; padding: 15px; margin-bottom: 20px;">
                        <h4 style="color: #155724; margin-top: 0;">✅ Email System Working</h4>
                        <p style="margin-bottom: 0; color: #155724;">
                            If you received this email, your Case-Verify AI email system is configured correctly!
                        </p>
                    </div>
                    
                    <p>This is a test email to verify that the email functionality is working properly.</p>
                    
                    <div style="text-align: center; margin-top: 30px; padding-top: 20px; border-top: 1px solid #dee2e6;">
                        <p style="color: #6c757d; font-size: 14px;">
                            Case-Verify AI Email System<br>
                            Generated on: {datetime}
                        </p>
                    </div>
                </div>
            </body>
        </html>
        """.format(datetime=self._get_current_datetime())
